### ISSUE TITLE
Library -> Browse Library did not work 

### ISSUE THREAD

**Issue by azataiot** [chocoford/ExcalidrawZ#10]
![CleanShot 2024-03-06 at 14 01 19](https://github.com/chocoford/ExcalidrawZ/assets/8280770/a28f5ea7-a8c2-4302-8ba0-61bae4ebecfe)

**Comment by chocoford** [comment]
Hello, @azataiot. The compatibility with Libraries has been added to the latest alpha version XD. You can download it from [here](https://github.com/chocoford/ExcalidrawZ/releases), and thank you for your love of ExcalidrawZ.

> [!WARNING]
> **Always remember to back up your files before updating to this alpha version.**
