### ISSUE TITLE
where is the default save path?

### ISSUE THREAD

**Issue by ixqbar** [chocoford/ExcalidrawZ#12]
where is the default save path?

**Comment by chocoford** [comment]
Hello @ixqbar. The excalidraw files are currently stored in database. You can export them to any place via the button on the right-top side of the app.

**Comment by ixqbar** [comment]
got! thanks!

**Comment by dserodio** [comment]
Even though it's stored in a database, IMHO the question is still valid. I just lost the data for a diagram, and I'm trying to locate the database to see if I could rescue the data.

**Comment by chocoford** [comment]
@dserodio Hello. Sorry for that.
Did you lose all the data, or the data of a single excalidraw file?

**Comment by dserodio** [comment]
It was the only diagram I had, to I can't tell if I lost all the data or not. But the File History feature worked to restore it. Thanks for the help and the quick response.
