### ISSUE TITLE
Solicitação de Personalização da Barra Superior no Aplicativo Excalidraw para macOS

### ISSUE THREAD

**Issue by leandrofelix-dev** [chocoford/ExcalidrawZ#13]
Gostaria de sugerir a possibilidade de personalização da barra superior no aplicativo Excalidraw para macOS. Em vez da barra superior padrão, seria interessante ter uma opção para uma barra personalizada ou até mesmo a remoção dela, com os botões de ação diretamente na tela do aplicativo.
Um abraço do Brasil!

![image](https://github.com/chocoford/ExcalidrawZ/assets/58048297/9726c547-05dc-4017-8838-91bba593770c)

**Comment by chocoford** [comment]
Obrigado pelo seu interesse e feedback! Isso é realmente uma ótima ideia. Vamos considerar essa sugestão no nosso próximo ciclo de desenvolvimento. Se essa funcionalidade for implementada, avisaremos você em primeira mão.

Um abraço!

**Comment by chocoford** [comment]
Olá, @leandrofelix-dev, obrigado pela sua sugestão. A nova versão alpha já moveu a barra de ferramentas para a barra superior do aplicativo e removeu a barra de ferramentas que estava acima da tela. Você pode baixar a versão de teste [aqui](https://github.com/chocoford/ExcalidrawZ/releases/tag/v1.0.0-alpha-1) para experimentar, ou pode esperar até que a versão oficial mais recente seja lançada.

**Comment by leandrofelix-dev** [comment]
@chocoford A nova versão ficou muito boa. Parabéns!

**Comment by chocoford** [comment]
Hola, se ha lanzado la nueva versión alfa. En esta versión se ha optimizado el rendimiento de carga de archivos. No olvides actualizar si ya instalaste la versión alfa-1.

https://github.com/chocoford/ExcalidrawZ/releases/tag/v1.0.0-alpha-2

Não se esqueça de arquivar seus arquivos antes de atualizar para a versão alpha.
