### ISSUE TITLE
Cannot add image

### ISSUE THREAD

**Issue by nank1ro** [chocoford/ExcalidrawZ#14]

**Comment by chocoford** [comment]
Hello, thank you for your feedback. What were your steps? I just tried methods like copy and paste, dragging and dropping to add images, and found that the functions are working properly.

**Comment by nank1ro** [comment]
I click on the image button (9), drag where to place the image, but no picker is shown.
I'm on Sonoma 14.4.1 MacBook Pro M1
<img width="1238" alt="Screenshot 2024-07-11 at 12 57 22" src="https://github.com/chocoford/ExcalidrawZ/assets/60045235/4864356f-fd13-4e1a-9380-76fde9479f1a">

**Comment by chocoford** [comment]
Hello, @nank1ro. The new alpha test version of `ExcalidrawZ` has fixed this issue. You can download [here](https://github.com/chocoford/ExcalidrawZ/releases/tag/v1.0.0-alpha-1) or you can wait for the formal version.

**Don't forget to achive your files before you updating to the alpha version**

**Comment by nank1ro** [comment]
> here

Yep, it worked perfectly.
Thank you so much 🙏

Feel free to close it
