### ISSUE TITLE
Duplicated sidebar toggle on macOS 15

### ISSUE THREAD

**Issue by DervexDev** [chocoford/ExcalidrawZ#15]
On macOS Sequoia Developer Beta 4 sidebar toggle is duplicated:

![Screenshot 2024-07-23 at 11 49 36 PM](https://github.com/user-attachments/assets/ada83794-e7e6-49b5-b89d-19d35dc67176)

I suspect that it is caused by the `removeSidebarToggle` function from your `ChocofordKit` not working properly on the latest macOS. This snippet particularly:

```swift
if let index = toolbarItems?.firstIndex(where: { $0.itemIdentifier.rawValue == "com.apple.SwiftUI.navigationSplitView.toggleSidebar" }) {
    toolbar?.removeItem(at: index)
}
```

**Comment by chocoford** [comment]
Thank you for your feedback; I will fix this issue as soon as possible.

**Comment by chocoford** [comment]
This is fixed in the latest release.

**Comment by DervexDev** [comment]
Thanks for the quick update!
