### ISSUE TITLE
After updating to the latest version(0.4.4), some keys, including the spacebar, do not work

### ISSUE THREAD

**Issue by mooncastlestone** [chocoford/ExcalidrawZ#17]
Hello!

First of all, thank you very much for this app. Thanks to you, I've been using it very well.

However, after updating to the latest version, I ran into a problem which some keys, including the spacebar, don't work.

To resolve this, I tried downgrading to the previous version(0.4.3), and everything worked properly.

I would appreciate if if you could fix this issue.

### Version
macOs : Sonoma 14.5

**Comment by chocoford** [comment]
Hello, I have conducted real device tests on macOS 14.1 and 14.5 and did not encounter the issue of ‘multiple keys (including the space bar) not working’ that you mentioned. If possible, could you provide a more detailed reproduction path? Thank you for your feedback.

**Comment by saiumesh-appfire** [comment]
Hey, @mooncastlestone I've same issue. When I enter letter S app freezes and not able to enter other characters. @chocoford

**Comment by chocoford** [comment]
The new hot-fix version 0.4.5 has been released. I apologize for the inconvenience caused by this unsuccessful update.
