### ISSUE TITLE
Please🙏 make the app compatible with older version of macOS

### ISSUE THREAD

**Issue by spiljj** [chocoford/ExcalidrawZ#18]
I finally found this offline version of Excalidraw written in Swift, thinking it could replace Freeform (which does not support Monterey). However my Mac can only stay on the Monterey system and cannot be upgraded, this is such a pity. I kindly request the developer if you could develop a version compatible with Monterey, or guide me on how to compile the source code to make it work?

**Comment by chocoford** [comment]
Hello @spiljj. Thank you for your interest in ExcalidrawZ. As for compatibility with macOS Monterey, I need to evaluate the involved APIs further. Development of the new version of ExcalidrawZ is already underway, and if possible, I will extend compatibility to Monterey.

**Comment by spiljj** [comment]
> Hello @spiljj. Thank you for your interest in ExcalidrawZ. As for compatibility with macOS Monterey, I need to evaluate the involved APIs further. Development of the new version of ExcalidrawZ is already underway, and if possible, I will extend compatibility to Monterey.

Thank you so much! Keep up the good work🥳Fingers crossed for good news...

**Comment by spiljj** [comment]
> Hello @spiljj. The new alpha test version of `ExcalidrawZ` has been released, including compatibility with macOS 12. You can download it [here](https://github.com/chocoford/ExcalidrawZ/releases/tag/v1.0.0-alpha-3). If you encounter any issues with the software, please let me know. Thank you.

谢谢你！
I will evaluate this. Thank you so much. I believe this will boost my productivity!
