### ISSUE TITLE
How to add Excalidraw Libraries?

### ISSUE THREAD

**Issue by sagar-18** [chocoford/ExcalidrawZ#22]
How to add Excalidraw Libraries?

**Comment by chocoford** [comment]
Hello. @sagar-18. 
Sorry, compatibility with the `Libraries` is still under development and is planned to be released along with the official 1.0.0 version.

**Comment by sagar-18** [comment]
Okay, Thank you

**Comment by chocoford** [comment]
Hello, @sagar-18. The compatibility with Libraries has been added to the latest alpha version XD. You can download it from [here](https://github.com/chocoford/ExcalidrawZ/releases), and thank you for your love of ExcalidrawZ.

> [!WARNING]
> **Always remember to back up your files before updating to this alpha version.**

**Comment by dserodio** [comment]
Sorry for the silly question, but how can I import libraries in 1.1.0? I tried **File → Import** but it doesn't support `.excalidrawlib` files

**Comment by chocoford** [comment]
Hello, @dserodio 

I’m sorry the UI caused you confusion. Your intuition is correct—the import option on the toolbar should also work for the library.

For now, you can open the library by clicking the trailing-sidebar button in the top-right corner of the app. Then, you can import the library by either dragging and dropping or clicking to upload.
