### ISSUE TITLE
Homebrew support

### ISSUE THREAD

**Issue by mayurankv** [chocoford/ExcalidrawZ#23]
Would it be possible to add this to homebrew as a cask? This would make updating much easier!

**Comment by chocoford** [comment]
For the upcoming version, the current plan is to synchronize the release of both the App Store and GitHub versions (with version updates supported by the Sparkle framework). I will evaluate the possibility of releasing it as a Homebrew cask. Thank you for your suggestion.

**Comment by mayurankv** [comment]
Thank you so much! Other benefits of homebrew involve portability across other devices so when changing laptops, one can quickly reinstall applications without finding the original sources! Also it generally makes the installation process very easy (terminal one-liner) and its pretty easy to [create a cask](https://docs.brew.sh/Adding-Software-to-Homebrew). I try to generally make all the apps downloaded either through the app store or homebrew where there is a clear store of where it is downloaded from! If you're open to the idea but too busy with other things, I'd be happy to take a look!

You also mentioned an App Store version but I was unable to find this. Is it the current plan to publish the app for free on the app store? or for a fee? I totally understand that developer licenses cost money, and if the plan is to charge a fee for the convenience of the app store, then it probably makes sense to not create a homebrew cask.

Thank you for your consideration! :))

**Comment by karlhorky** [comment]
Looks like the App Store version may be available now:

- https://apps.apple.com/us/app/excalidrawz/id6636493997?mt=12

**Comment by chocoford** [comment]
Hello! I’m currently working on it. Sorry for keeping you waiting for so long.

**Comment by karlhorky** [comment]
Oh, no worries! Thanks for all of your effort here 🙌

**Comment by chocoford** [comment]
@karlhorky  @mayurankv 
Sorry for the wait! ExcalidrawZ should now be installable via Homebrew cask. You can give it a try!​⬤
If you encounter any issues, please let me know right away.
I am new to Homebrew cask😁

**Comment by karlhorky** [comment]
Nice, looks like [this `excalidrawz` cask here](https://formulae.brew.sh/cask/excalidrawz) I guess?

```bash
brew install --cask excalidrawz
```

**Comment by chocoford** [comment]
Yes, you can also install it directly using `brew install excalidrawz`.
