### ISSUE TITLE
Donate Button

### ISSUE THREAD

**Issue by jfuqua7** [chocoford/ExcalidrawZ#33]
I would love to give you a donation to your project. I have been an Excalidraw user for over 3 years and I have been using Obsidian with the plugin, but this makes sharing drawings terrible. Your tool is perfect.

**Comment by chocoford** [comment]
Thank you very much for your love and appreciation for ExcalidrawZ. 
The integration of donation is on the way 😁.

If you have any needs or suggestions, please do not hesitate to bring them up.

**Comment by chocoford** [comment]
Hi @jfuqua7, I’m happy to tell you that I finally managed to set up the donation channel, so you can buy me a coffee here.

<a href="https://www.buymeacoffee.com/Chocoford" target="_blank"><img src="https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png" alt="Buy Me A Coffee" style="height: 30px !important;" ></a>

 By the way, if you update the app, the annoying sound when selecting the tool has gone. 
 If there are no other issues, I will close this issue. 😄

**Comment by chocoford** [comment]
buymeacoffee.com/Chocoford
