### ISSUE TITLE
Pasted image inverted in dark mode.

### ISSUE THREAD

**Issue by hyperphysin** [chocoford/ExcalidrawZ#34]
![Screenshot 2024-09-16 at 8 48 41 AM](https://github.com/user-attachments/assets/16451690-32e1-4fcb-95a9-513233e7f256)

**Comment by chocoford** [comment]
I’m sorry for the inconvenience. 
Currently, reversing the colors of images in dark mode is a feature of Excalidraw. You can prevent images from being reversed by changing the color mode of Excalidraw in the settings.

But you’ve given me an idea :D. Perhaps in future versions, I should add a setting regarding the reversal of image colors.

**Comment by chocoford** [comment]
In the latest version of ExcalidrawZ(v1.2.3), image can be prevented to invert.
