### ISSUE TITLE
Feature Request - Window mode

### ISSUE THREAD

**Issue by socialstijn** [chocoford/ExcalidrawZ#44]
Hello first of all, great app. Thanks for developing it!

Is there a way that you can add window mode, where you can open a drawing in a single window. This is useful when for example sharing a single drawing via Zoom or Microsoft Teams.

**Comment by socialstijn** [comment]
Missed the New Window option, thanks!

**Comment by chocoford** [comment]
@socialstijn Hello, thank you for your suggestion. I will look into implementing this feature.

For now, you can export an .excalidraw file and double-click it to open in single-window editing mode. Please note that any changes made will be immediately reflected in the file.
