### ISSUE TITLE
Making overriding the DEVELOPMENT_TEAM easier

### ISSUE THREAD

**Issue by DivineDominion** [chocoford/ExcalidrawZ#47]
All app projects require a developer team setting -- and as an open source app contributor, it's almost never the team of my account :)

![2024-11-23 08-39-35 Xcode - ExcalidrawZ — ExcalidrawZ xcodeproj@2x](https://github.com/user-attachments/assets/6d3dd1c8-5b16-43fa-ae40-ceee8ee54b75)

Changing the dev team setting in the Xcode project works, but this can easily be checked in by accident (since adding files also changes the project).

Xcode config files can help here because they permit optional overrides, i.e. from files that may not exist, and which contributors could add (if they want):

## Add optional local overrides to Xcode build settings

Xcode project build settings are, by default, stored in the `.xcodeproj` file. This includes the `DEVELOPMENT_TEAM` setting, which makes collaboration hard if you don't share the dev team identity with e.g. freelancers.

1. Extract `.xcconfig` files from the project using e.g. <https://buildsettingextractor.com/>. These config files scale better and are easier to diff.

2. Import optional overrides using `#include? "Overrides.xcconfig"` which doesn't fail if the file does not exist.[source][20211120xconf]
    - Add this file to `.gitignore` so collaborators can create it themselves. 
    - Add this file outside of the project directory to not worry about it.
    - Absolute (!) paths work, too, but not with `~` expansion, so no overrides in `~/.config/xcode/` :(

[20211120xconf]: https://pewpewthespells.com/blog/xcconfig_guide.html#includeStatements

## Suggested change

- Introduce `/Config/Project.xcconfig` with the current `DEVELOPMENT_TEAM="3XKM749Y3L";` value
- Add a line to optionally include local overrides from `/Config/Overrides.xcconfig`

**Comment by chocoford** [comment]
Hello,

Thank you very much! The issue you raised is very critical, and I hadn’t considered this point before.
