### ISSUE TITLE
Shortcut to move canvas triggers system alert sound.

### ISSUE THREAD

**Issue by Lcarv20** [chocoford/ExcalidrawZ#50]
Hi there,

When I press space + mouse click to move the canvas around it triggers the system alert sound continuously.

ps: thanks for this wrapper is amazing!!

**Comment by chocoford** [comment]
Hello, @frame 
 
After you use `space + mouse click` to move the canvas, to avoid subsequent actions triggering the system warning sound, you can use a tricky workaround—double-click anywhere to trigger text input and then cancel it.

In your case, after clicking on `Text (8)`, you need to actually trigger a text input box on the canvas. Only after this will the warning sound stop interrupting you.

I will work on fixing this issue in an upcoming version.

**Comment by frame** [comment]
Thank you! Your help is much appreciated.

> In your case, after clicking on Text (8), you need to actually trigger a text input box on the canvas. Only after this will the warning sound stop interrupting you.

I'm not able to pull this off, not sure why. I'm using [Karabiner Elements](https://karabiner-elements.pqrs.org) and [Mac Mouse Fix](https://macmousefix.com). Maybe they interfere as well.

But I just discovered another workaround that works for me and maybe is also helpful to other mouse users: The middle mouse button can also drag the canvas.

**Comment by chocoford** [comment]
Oh, sorry, I misunderstood the issue😂. You’re referring to the sound made during the drag process. 
Unfortunately, there’s no tricky workaround for this problem at the moment. 
I’ll work on fixing it as soon as possible—apologies for the inconvenience.

**Comment by Lcarv20** [comment]
I don't know enough of swift or application development for mac, so what I am about to say might sound stupid, but I wonder if you can specify the space+mouseClick as shortcut (and do nothing), maybe this will tell the system that it's not an invalid key combination.

**Comment by chocoford** [comment]
@Lcarv20 Yes, you are right. In fact, in earlier versions, all keys, including 0-9, would trigger warning sounds because the client couldn’t recognize all keydown events sent to Excalidraw. This issue was later fixed, but the space key was accidentally overlooked.

**Comment by chocoford** [comment]
Hello, @frame @Lcarv20. 
The new version of ExcalidrawZ (v1.2.5) has been released, which includes a fix for this issue.

**Comment by Lcarv20** [comment]
Thanks @chocoford. I haven't yet tried but will close for now!

**Comment by frame** [comment]
Just to confirm: 1.2.5 (28) fixed the issue for me. Thank you!
