### ISSUE TITLE
Enhancement: Separate Light/Dark Mode for Excalidraw WebView

### ISSUE THREAD

**Issue by The-Ducktor** [chocoford/ExcalidrawZ#6]
I would appreciate the ability to set a distinct light/dark mode for the Excalidraw webview, independent of the main UI settings. Currently, the webview inherits the mode from the overall UI and makes it so the images you have look inverted, and having a dedicated setting for the webview would enhance personalization options.

**Comment by chocoford** [comment]
Hello @The-Ducktor. That will be a great suggestion. We plan to update this feature in future versions.

**Comment by chocoford** [comment]
Hello @The-Ducktor . 
The new version of `Excalidraw` has been released, which include the feature of `set a distinct light/dark mode for the Excalidraw webview`.
You can download the new version via in-program updates or manually download here: https://github.com/chocoford/ExcalidrawZ/releases/tag/v0.4.3

**Comment by The-Ducktor** [comment]
Tried it works perfectly
