### ISSUE TITLE
Korean Text Disappearing Issue

### ISSUE THREAD

**Issue by jyoon17** [chocoford/ExcalidrawZ#60]
**Describe the bug**
I would like to report an issue related to the use of Korean characters. In certain situations, the text disappears while typing. For example, when typing the Korean character “하”, it requires entering “ㅎ” followed by “ㅏ”. However, during this process, the character disappears.

This issue does not occur in the online version of Excalidraw.

**To Reproduce**
1. Change the input method to Korean.
2. Type `ㅎ` followed by `ㅏ`.
3. Check if the character disappears.

**Desktop (please complete the following information):**
 - OS: macOS 15.1.1
 - Version(Build) 1.2.6

**Additional context**
- Installation source: `downloaded directly`
- Are you logged into an iCloud account?: Yes

**Screenshots**
![excal](https://github.com/user-attachments/assets/73c040ab-311d-4c84-90d7-b70da2e33ceb)

**Comment by jyoon17** [comment]
I believe this issue is caused by the handwriting font. As shown in the GIF below, the problem does not occur when using other fonts.
![font](https://github.com/user-attachments/assets/4427330b-d54e-400a-8363-94c8cf1214d7)

**Comment by chocoford** [comment]
Thank you for your feedback. I will include a fix for this issue in the next version update. In the upcoming version, the font “빙그레 싸만코체” will be used as the handwriting font for Korean.
![image](https://github.com/user-attachments/assets/2a7ef7cc-c403-4bf9-b603-ff62dbd71c2a)
