### ISSUE TITLE
Copy to clipboard as PNG doesn't copy inserted images

### ISSUE THREAD

**Issue by fharper** [chocoford/ExcalidrawZ#9]
If I inserted an image in my diagram, when I use the "Copy to clipboard as PNG" menu option, the diagram is copied, but without the inserted image. I tried to group it with diagram shapes, but it didn't work.

Amazing work by the way!

**Comment by chocoford** [comment]
Hi @fharper. Thank you for your feedback. We will promptly locate and fix the issue as soon as possible.

**Comment by chocoford** [comment]
Hi @fharper. Can you please offer me a `.excalidraw` file that is with the bug?

**Comment by chocoford** [comment]
Hello @fharper.
The new version of Excalidraw has been released, which include the fix of `"Copy to clipboard as PNG" not working`.
You can download the new version via in-program updates or manually download here: https://github.com/chocoford/ExcalidrawZ/releases/tag/v0.4.3
